name: Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cross-build:
    name: Build ${{ matrix.arch }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            name: linux
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            name: linux
            arch: aarch64
            target: aarch64-unknown-linux-gnu
          # Windows
          - os: windows-latest
            name: windows
            arch: x86_64
            target: x86_64-pc-windows-msvc
          - os: ubuntu-24.04
            name: windows
            arch: aarch64
            target: aarch64-pc-windows-gnullvm
          # MacOS
          - os: macos-latest
            name: macos
            arch: x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            name: macos
            arch: aarch64
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
          qemu: '9.2'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-v1
      - name: Setup Windows ARM64
        run: export OPENSSL_NO_VENDOR=1
        if: ${{ matrix.name }} == 'windows' && ${{ matrix.arch }} == 'aarch64'
      # - name: Setup Windows ARM64
      #  uses: crazy-max/ghaction-chocolatey@v3
      #  if: matrix.name == 'windows' && matrix.arch == 'aarch64'
      #  with:
      #    args: install -y visualstudio2022-workload-vctools --params "--add Microsoft.VisualStudio.Component.VC.Tools.ARM64"
      - name: Check code format
        run: cargo fmt --all -- --check
      #      - uses: taiki-e/install-action@nextest
      #      - name: Test
      #        run: cargo nextest run --no-fail-fast --all-features
      - run: cargo install catppuccin-whiskers
      #      - name: Install rust packager
      #        run: |
      #          cargo install cargo-packager --locked
      #          cargo packager --release --target ${{ matrix.target }}
      - run: |
          echo ${OPENSSL_NO_VENDOR}
          cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: |
            target/${{ matrix.target }}/release/nxshell*
            !target/${{ matrix.target }}/release/*.d
            !target/${{ matrix.target }}/release/*.pdb
          name: nxshell-${{ matrix.name }}-${{ matrix.arch }}
          compression-level: 9

